### ISSUE TITLE
alpha-sudo-shell-command: "Cannot execute command" error for "apt search color"

### ISSUE THREAD

**Issue by hai-nc** [alpha-catharsis/alpha-sudo#1]
Code loaded fine on my Emacs 27.1 Debian; however, when I ran (alpha-sudo-shell-command "apt search color") I got the error "Cannot exectute command ‘apt search color’ via sudo".

When I tried debugging the function, I got to the function `alpha-sudo-can-p' where `alpha--call-process' complained that '(1 "sudo: a terminal is required to read the password;...")'.

**Comment by alpha-catharsis** [comment]
Thank you very much for reporting the issue.
Unfortunately it is not easy to reproduce the problem in my setup.
Would you be so kind to answer the following questions?

1. If you run `sudo -l apt` in your terminal, does sudo ask for your password?
2. If you run `sudo -l` in your terminal, does sudo ask for your password?
3. Does anything change if you replace the body of alpha--call-process with the following code?

`
(with-temp-buffer
    (let ((command (string-join (cons program args) " ")))
      (let ((exitcode (call-process-shell-command command nil (current-buffer) nil)))
      (list exitcode (buffer-string))))))
`

Thanks

**Comment by alpha-catharsis** [comment]
I have tested the package through docker on debian and some other distros and everything seems fine. Eventually I managed to reproduce the issue removing any sudo authorization from file /etc/sudoers from the user. So I believe that simply you do not have authorization to run sudo on your machine. You can verify this by running `sudo -vn`. So, in the end, the message "Cannot execute command 'xxx' via sudo" is correct.
Could you please confirm this so I can close the issue?

**Comment by hai-nc** [comment]
Hi,

>     1. If you run `sudo -l apt` in your terminal, does sudo ask for your password?
Yes.

>     2. If you run `sudo -l` in your terminal, does sudo ask for your password?
Yes. 

>     3. Does anything change if you replace the body of alpha--call-process with the following code?
No, I still got the issue.

> verify this by running sudo -vn
I got 0 exit code when running so. 

I tried it on Debian Sid (Linux debian 5.9.0-5-amd64 #1 SMP Debian 5.9.15-1 (2020-12-17) x86_64 GNU/Linux).

By the way, I tried `M-x alpha-sudo-shell-command' on Emacs in terminal mode (running Emacs via 'emacs -nw') when I got the error message. My Emacs environment variable $TERM that I tried include "dumb" (the default value) and "xterm256", if it is of any relevance.

**Comment by alpha-catharsis** [comment]
Thank you very much for the information. It allowed me to to reproduce the problem. My understanding on whether sudo asks for password when invoked with -l argument was incomplete (it can vary depending on some settings in /etc/sudoers). I will study more in depth the sudo documentation, test the different cases and update the package to solve this issue.

**Comment by alpha-catharsis** [comment]
I have just released a new version of the package that should fix this issue. Could you please try it out and confirm that the issue is solved?

**Comment by hai-nc** [comment]
It worked with both `alpha-sudo-shell-command' and `alpha-sudo-program'.

Thank you for your hard work and amazing response.
