### ISSUE TITLE
The URL field is not correct

### ISSUE THREAD

**Issue by snogge** [alpha-catharsis/alpha-sudo#2]
The URL here
### https://github.com/alpha-catharsis/sudo-utils/blob/82aa6f53762f366f589c4b6df74d575dd5d86a1c/sudo-utils.el#L9
is not correct.  The github project name does not include '.el'

**Comment by alpha-catharsis** [comment]
Thank you very much for pointing out the issue. I have fixed it.
Given the trivial nature of the issue, I proactively mark it as closed.
